spring:
  application:
    name: publi-connect
  r2dbc:
    # For development, the springboot docker compose dependency runs automatically the docker compose up
    # Just move the docker compose yml from the publi-connect-infra repo into the backend folder
    # and use the env file example for running and test it
    # url: ${DB_URL}
    # username: ${DB_USER}
    # password: ${DB_PWD}
    pool:
      max-acquire-time: 30s
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}
jwt:
  secret:
    key: ${JWT_KEY}
  expiration:
    time: 86400000
  refresh:
    time: 25920000000
cors:
  allowed-origins: ${FRONT_ORIGIN:http://localhost:5173}
cookies:
  secure: false
  same-site: Lax
