spring:
  application:
    name: publi-connect
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    pool:
      max-acquire-time: 30s
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}
jwt:
  secret:
    key: ${JWT_KEY}
  expiration:
    time: 86400000
  refresh:
    time: 25920000000
