spring:
  config:
    import:
      - "aws-secretsmanager:app/publi-connect"
      - "aws-secretsmanager:rds!db-1996bf7c-897b-45d6-aac5-2d60dfcaba0c"
  cloud:
    aws:
      region:
        static: us-east-2
  application:
    name: publi-connect
  r2dbc:
    username: ${username}
    password: ${password}
    pool:
        max-acquire-time: 30s
        initial-size: 5
        max-size: 20
        max-idle-time: 30m
cookies:
  secure: true
  same-site: None
jwt:
  expiration:
    time: 86400000
  refresh:
    time: 25920000000
